# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '11.x'
    displayName: 'Install Node.js'

  - script: |
      yarn
      yarn lint
      yarn test
    displayName: 'Install and test'

  - script: yarn build:site
    displayName: 'Build site'

  - task: Docker@1
    displayName: 'Build Docker image'

  - task: Docker@1
    inputs:
      command: 'push'
      dockerRegistryConnection: 'Docker'
    displayName: 'Push Docker image'
